"""Sample questions used to steer generation style by coupley-ness."""

PERSONAL = [
    "If you could become world-class at one thing, what would it be?",
    "What’s something you believe that most people in your life would disagree with?",
    "What’s the best decision you’ve made in the last year?",
    "What’s something you want that you’re slightly embarrassed to admit?",
    "When do you feel most like yourself?",
    "What’s a question nobody has ever asked you that you wish they would?",
    "What’s something you used to believe that you completely changed your mind about?",
    "What does an ideal week look like for you?",
    "What’s something you’ve never done that you think you’d be good at?",
    "What’s the most interesting failure you’ve had?",
    "What do you think people misunderstand about you?",
    "What’s one thing you want to experience before you die that you haven’t told anyone?",
    "What would you do differently if nobody was watching?",
]

COUPLE = [
    "What was your first impression of me, and what has changed since then?",
    "What moment in our relationship made you feel closest to me?",
    "What’s something small I do that makes you feel loved?",
    "What’s one thing you wish we did more often together?",
    "What do you think we bring out in each other?",
    "What’s a memory of us that always makes you smile?",
    "When have you felt most supported by me?",
    "What’s something you’ve learned about love from being with me?",
    "What do you think makes our relationship different from your past relationships?",
    "What’s something about me you appreciate but rarely say out loud?",
    "What’s one way I could understand you better?",
    "What makes you feel safest in a relationship?",
    "When you’re upset, what kind of support actually helps you?",
    "What’s something you find difficult to ask for?",
    "What’s a fear you have about relationships that you don’t often talk about?",
    "What does commitment mean to you?",
    "What does a healthy disagreement look like to you?",
    "What’s one relationship habit you want us to protect?",
    "What’s one relationship habit you’d like us to improve?",
    "When do you feel most emotionally connected to me?",
    "What makes you feel desired?",
    "What makes you feel appreciated?",
    "What’s something you hope never changes about us?",
    "What kind of life would make you feel genuinely successful?",
    "Where do you imagine us living five years from now?",
    "What’s one adventure you’d love for us to take together?",
    "What tradition would you like us to create?",
    "What would our perfect ordinary Sunday look like?",
    "What’s something you’d love for us to learn together?",
    "What financial goal would feel exciting for us to work toward?",
    "What do you want our home to feel like?",
    "What’s one thing you want our future selves to thank us for?",
    "If we could take a month off with no responsibilities, how would we spend it?",
    "What silly thing do you think we’d be unusually good at as a team?",
    "What fictional couple are we most similar to?",
    "What’s one date you’ve always wanted someone to plan for you?",
]

ALL_SAMPLES = PERSONAL + COUPLE
